--
-- You need to replace ORACLE_HOME for your own Path.
CREATE TABLESPACE RU_DAT DATAFILE 
  'ORACLE_HOME\RU_DAT.DBF' SIZE 2M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 40K
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

--

CREATE TABLESPACE RU_IDX DATAFILE 
  'ORACLE_HOME\RU_IDX.DBF' SIZE 1M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 40K
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

--
-- You should change the user's password
CREATE USER RU
  IDENTIFIED BY RU
  DEFAULT TABLESPACE RU_DAT
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT RESOURCE TO RU;
  GRANT CONNECT TO RU;
  ALTER USER RU DEFAULT ROLE ALL;
  GRANT ALTER USER TO RU;
  GRANT CREATE SESSION TO RU;
  GRANT CREATE PROCEDURE TO RU;
  GRANT UNLIMITED TABLESPACE TO RU;
  GRANT CREATE ANY INDEX TO RU;
  GRANT CREATE VIEW TO RU;
  GRANT CREATE PUBLIC SYNONYM TO RU;
  ALTER USER RU QUOTA UNLIMITED ON RU_DAT;
  ALTER USER RU QUOTA UNLIMITED ON RU_IDX;

--
-- Tables
CREATE TABLE RU.RU_ENCARGADOS_RUTAS
(
  COD_COMPANIA      VARCHAR2(4 BYTE)                 NOT NULL,
  COD_ENCARGADO     NUMBER(10)                       NOT NULL,
  NOMBRE            VARCHAR2(100),
  PRIMER_APELLIDO   VARCHAR2(100),
  SEGUNDO_APELLIDO  VARCHAR2(100),
  NOMBRE_ENCARGADO  VARCHAR2(300),
  COD_ESTADO        VARCHAR2(4 BYTE)                 DEFAULT 'ACT',
  USER_REG          VARCHAR2(30 BYTE),
  FECHA_REG         DATE,
  USER_MOD          VARCHAR2(30 BYTE),
  FECHA_MOD         DATE
)
TABLESPACE RU_DAT
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10880K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RU.PK_RU_ENCARGADOS_RUTAS ON RU.RU_ENCARGADOS_RUTAS
(COD_COMPANIA, COD_ENCARGADO)
LOGGING
TABLESPACE RU_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4160K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM RU_ENCARGADOS_RUTAS FOR RU.RU_ENCARGADOS_RUTAS;


ALTER TABLE RU.RU_ENCARGADOS_RUTAS ADD (
  CONSTRAINT PK_RU_ENCARGADOS_RUTAS
 PRIMARY KEY
 (COD_COMPANIA, COD_ENCARGADO)
    USING INDEX 
    TABLESPACE RU_IDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          4160K
                NEXT             40K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE RU.RU_ENCARGADOS_RUTAS
 ADD CONSTRAINT FK_PA_COMPANIA_ENCARGADO_RUTA
 FOREIGN KEY (COD_COMPANIA) 
 REFERENCES PA.PA_COMPANIAS (COD_COMPANIA);

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RU.RU_ENCARGADOS_RUTAS TO PUBLIC;

--
--
CREATE TABLE RU.RU_RUTAS
(
  COD_COMPANIA      VARCHAR2(4 BYTE)                 NOT NULL,
  COD_RUTA          NUMBER(10)                       NOT NULL,
  DES_RUTA          VARCHAR2(100),
  COD_ENCARGADO     NUMBER(10),
  COD_ESTADO        VARCHAR2(4 BYTE)                 DEFAULT 'ACT',
  USER_REG          VARCHAR2(30 BYTE),
  FECHA_REG         DATE,
  USER_MOD          VARCHAR2(30 BYTE),
  FECHA_MOD         DATE
)
TABLESPACE RU_DAT
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10880K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RU.PK_RU_RUTAS ON RU.RU_RUTAS
(COD_COMPANIA, COD_RUTA)
LOGGING
TABLESPACE RU_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4160K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE PUBLIC SYNONYM RU_RUTAS FOR RU.RU_RUTAS;


ALTER TABLE RU.RU_RUTAS ADD (
  CONSTRAINT PK_RU_RUTAS
 PRIMARY KEY
 (COD_COMPANIA, COD_RUTA)
    USING INDEX 
    TABLESPACE RU_IDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          4160K
                NEXT             40K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ));

ALTER TABLE RU.RU_RUTAS
 ADD CONSTRAINT FK_PA_COMPANIA_RU_RUTAS 
 FOREIGN KEY (COD_COMPANIA) 
 REFERENCES PA.PA_COMPANIAS (COD_COMPANIA);
 
ALTER TABLE RU.RU_RUTAS
 ADD CONSTRAINT FK_ENCARGADOS_RUTAS_RU_RUTAS 
 FOREIGN KEY (COD_COMPANIA, COD_ENCARGADO) 
 REFERENCES RU.RU_ENCARGADOS_RUTAS (COD_COMPANIA, COD_ENCARGADO);

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RU.RU_RUTAS TO PUBLIC;

--
--
CREATE SEQUENCE RU.SQ_CODRUTA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999
NOCACHE 
NOCYCLE 
NOORDER;

GRANT SELECT ON RU.SQ_CODRUTA TO PUBLIC;

CREATE PUBLIC SYNONYM SQ_CODRUTA FOR RU.SQ_CODRUTA;
 
--
--
CREATE SEQUENCE RU.SQ_CODENCARGADO
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999
NOCACHE 
NOCYCLE 
NOORDER;

GRANT SELECT ON RU.SQ_CODENCARGADO TO PUBLIC;

CREATE PUBLIC SYNONYM SQ_CODENCARGADO FOR RU.SQ_CODENCARGADO;

--
--

CREATE OR REPLACE TRIGGER RU.TRG_RU_ENCARGADOS_RUTAS_NOMBRE
   BEFORE INSERT OR UPDATE OF 
   NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO ON 
   RU.RU_ENCARGADOS_RUTAS 
 REFERENCING NEW AS New OLD AS Old
 FOR EACH ROW
BEGIN
  --
  :NEW.Nombre_Encargado := SUBSTR(:NEW.Nombre||' '||:NEW.Primer_Apellido||' '||:NEW.Segundo_Apellido, 0, 300);
  --
END;

--
--

--
--
CREATE OR REPLACE FUNCTION RU.OBT_NOM_RUTA(pCodCompania IN  VARCHAR2, 
                                           pCodRuta     IN  NUMBER,
                                           pEstadoEj    OUT BOOLEAN,
                                           pError       OUT VARCHAR2
                                          ) RETURN VARCHAR2 IS  
   --
   --  Se encarga de obtener el nombre de la ruta
   --
   vNomRuta  VARCHAR2(100);
   --
BEGIN
   --  
   Select Des_Ruta
     into vNomRuta
     from Ru_Rutas
    where Cod_Compania = pCodCompania
      and Cod_Ruta     = pCodRuta;
   --
   pEstadoEj := TRUE;
   --
   Return vNomRuta;
   --
EXCEPTION
   WHEN NO_DATA_FOUND THEN
       pEstadoEj := FALSE;
       pError    := 'La ruta '||pCodRuta||' no existe';
       Return NULL;
   WHEN OTHERS THEN
       pEstadoEj := FALSE;
       pError    := 'Error al consultar la descripción de la ruta - '||Sqlerrm;
       Return NULL;
END;

GRANT EXECUTE ON RU.OBT_NOM_RUTA TO PUBLIC;

CREATE PUBLIC SYNONYM OBT_NOM_RUTA FOR RU.OBT_NOM_RUTA;

--
--